In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
July = pd.read_csv('../July.csv', index_col=0)
July = July.iloc[::3]
July.reset_index(inplace=True, drop=True)

In [4]:
def interpolate(RH_in):
    kf1 = [1.37, 1.48, 1.726, 1.35, 1.78]
    kf2 = [1.71, 12.67,  33.39, 2.06, 14.54]
    T = [298, 299, 298, 308, 308]
    vol = [0.002, 0.01, 0.02, 0.01, 0.02]
    RH_list = []

    for i in range(len(T)):
        P_H2O_sat = np.exp(77.34 - 7235/T[i]-8.2*np.log(T[i]) + 0.005711*T[i])
        P_H2O = 1e5*vol[i]
        RH_list.append(P_H2O/P_H2O_sat*100)

    RH_kf = np.array([RH_list, kf1, kf2]).T
    RH_kf = RH_kf[RH_kf[:, 0].argsort()]

    kf1_hat = np.interp(RH_in, RH_kf[:, 0], RH_kf[:, 1])
    kf2_hat = np.interp(RH_in, RH_kf[:, 0], RH_kf[:, 2])

    return kf1_hat, kf2_hat

def H2O_vol(T_g, RH, P):
    P_H2O_sat = 0.61078*np.exp(17.269*(T_g-273.15)/(T_g-273.15+237.29))*1000
    P_H2O = P_H2O_sat*RH
    vol = P_H2O/P
    return vol

In [5]:
import subprocess
import os
import time
import sys
import logging
from threading import Timer
import psutil
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
import pandas as pd


def gPLOT2df(filename):
    """
    Convert .gPLOT file to a pandas dataframe

    Args:
        filename (str) : Name of the gPLOT file.

    Returns:
        df (DataFrame): Pandas dataframe with the time indexes on the rows and the variables on the columns.
    """
    with open(filename, 'r') as f:
        # Read the first line with the number of variables
        nvar = int(f.readline())
        # Read the variablenames
        vars = [f.readline().strip() for i in range(0, nvar)]
        # Read the variablevalues at each time point
        df = pd.read_csv(f, header=None, index_col=False)
        ntime = int((len(df) - 1) / (nvar + 1))
        # Reshape and drop termination element
        df = pd.DataFrame(data=df.values[0:-1].reshape((ntime, nvar + 1)), columns=['Time'] + vars)
    return df

In [7]:
def call_gORUN(gORUN_path, gENCRYPT_name, activity, process, password, working_dir='./', time_out=24*3600,
               verbose=True):
    """
    Calls gORUN and waits for the execution to complete.

    Args:
        gORUN (str): Path to gORUN.bat (must end with gORUN.bat)
        gENCRYPT_name (str): Name of the gENCRYPT file to execute
        activity (str): Activity type  ('sim'|'opt'|'est')
        process (str): Name of the process in the gPROMS file
        password (str): Encryption password of the process in the gPROMS file
        timeout (float): Time out in seconds. After this time the gO:RUN process will be terminated.
        working_dir (str): If the function is not called from the directory containing the input directory,
            use this to change to the right working directory first. The working directory will be set back to the
            original one before terminating.

    Returns:
        result (logical): Returns True for succes, False for error
    """
    # Start timer
    start_time = time.time()

    mpicmd_part_1 = "mpiexec.exe -n 1 -localonly"
    mpicmd_part_2 = "-mpmd"
    mpicmd_part_3 = ": -n NW gCluster.exe"

    # Construct gORUN command
    #gORUN_cmd = [gORUN_path, gENCRYPT_name, activity, process, password]
    gORUN_options =  gENCRYPT_name + " " +  activity + " " +  process + " " +  password
    gORUN_output = ' > ' + activity + '_output.txt'

    np=1
    if np > 1:
        gORUN_path = gORUN_path.rstrip('.bat') + '.exe'
        gORUN_cmd = mpicmd_part_1 + " \"" + gORUN_path + "\" " + mpicmd_part_2 + " " + gORUN_options + " " + \
                    mpicmd_part_3
    else:
        gORUN_cmd = gORUN_path + " " + gORUN_options + gORUN_output
    # Run gO:RUN and log output to file
#    try:
#        with open('./pygORUN.log', 'w') as f:
#     f = open('test.log', 'wb')

    #print(gORUN_cmd)
    print('gPROMS executed')
    process = subprocess.Popen(gORUN_cmd, cwd=working_dir,
                                       encoding='ascii')
#            for line in iter(process.stdout.readline, ""):
#                if verbose:
#                    sys.stdout.write(line)
#                f.write(line.rstrip('\n'))
#                f.flush()
#   except subprocess.CalledProcessError as e:
#        logging.error('Error calling gO:RUN')

    my_timer = Timer(time_out, lambda: kill_process(process))

    try:
        my_timer.start()
        output, error = process.communicate()
    finally:
        my_timer.cancel()

    elapsed_time = time.time() - start_time
    if elapsed_time > time_out:
        print("Activity timed out")


    if process.returncode == 0 and elapsed_time < time_out:
        return True
    else:
        return False

def kill_process(process_to_kill,timestamp="zzz"):
    # ----------------------------------------------------------------------------------------------
    # FEP new solution on killing gORUNs that hang
    try:
        parent = psutil.Process(process_to_kill.pid)
        children = parent.children(recursive=True)
        for child in children:
            child.kill()
        psutil.wait_procs(children, timeout=1)

        # having cleaned up all the children also clean up self
        process_to_kill.terminate()

    except:
        print("Unable to kill")
        pass

In [8]:
h2o_temp = np.zeros(July.shape[0])

for i in range(July.shape[0]):
    if July['tmpK'].iloc[i] <= 278:
        h2o_temp[i] = 278
    elif July['tmpK'].iloc[i] >= 303:
        h2o_temp[i] = 303
    else:
        h2o_temp[i] = July['tmpK'].iloc[i]

July['h2o_temperature'] = h2o_temp

kf1 = np.zeros(July.shape[0])
kf2 = np.zeros(July.shape[0])

for i in range(July.shape[0]):
    kf1[i], kf2[i] = interpolate([July['relh'].iloc[i]])

July['kf1, bar-1 s-1 (mol/kg)-1'] = kf1
July['kf2, bar2 s-1'] = kf2
July['pressure'] = 96890

July['H2O_vol'] = H2O_vol(July['tmpK'], July['relh']*0.01, July['pressure'])
July

,station,valid,tmpc,relh,sped,tmpK,index,YEAR,DOY,HOUR,RING,CO2,WIND,WIND_DIR,SOLAR_ANG,h2o_temperature,"kf1, bar-1 s-1 (mol/kg)-1","kf2, bar2 s-1",pressure,H2O_vol
0,OQT,2008-07-01 00:53:00,22.78,42.48,3.45,295.93,8395,2008,182,0,0,496.1,1.38,260,-30.77,295.93,1.767537,18.890409,96890,0.012154
1,OQT,2008-07-01 03:53:00,16.67,69.51,0.00,289.82,8410,2008,182,3,0,479.6,1.18,220,-18.63,289.82,1.726000,33.390000,96890,0.013613
2,OQT,2008-07-01 06:53:00,13.89,83.21,0.00,287.04,8425,2008,182,6,0,488.6,1.13,260,11.32,287.04,1.726000,33.390000,96890,0.013631
3,OQT,2008-07-01 09:53:00,12.22,89.95,0.00,285.37,8440,2008,182,9,0,375.6,2.01,240,47.09,285.37,1.726000,33.390000,96890,0.013210
4,OQT,2008-07-01 12:53:00,17.78,72.53,0.00,290.93,8455,2008,182,12,0,369.5,1.99,220,76.47,290.93,1.726000,33.390000,96890,0.015237
5,OQT,2008-07-01 15:53:00,25.56,37.38,5.75,298.71,8470,2008,182,15,0,365.8,3.32,260,51.45,298.71,1.777381,15.454184,96890,0.012634
6,OQT,2008-07-01 18:53:00,27.78,32.84,0.00,300.93,8485,2008,182,18,0,366.1,1.41,320,15.35,300.93,1.617310,13.525897,96890,0.012648
7,OQT,2008-07-01 21:53:00,28.89,26.55,5.75,302.04,8500,2008,182,21,0,429.2,0.35,240,-15.69,302.04,1.441419,9.521196,96890,0.010906
8,OQT,2008-07-02 00:53:00,25.00,38.74,0.00,298.15,8515,2008,183,0,0,483.6,0.37,0,-30.83,298.15,1.774756,16.370511,96890,0.012665
9,OQT,2008-07-02 03:53:00,18.33,70.28,0.00,291.48,8530,2008,183,3,0,525.5,0.29,260,-18.71,291.48,1.726000,33.390000,96890,0.015284
10,OQT,2008-07-02 06:53:00,15.56,80.19,0.00,288.71,8545,2008,183,6,0,532.3,0.19,260,11.24,288.71,1.726000,33.390000,96890,0.014630
11,OQT,2008-07-02 09:53:00,13.89,86.58,0.00,287.04,8560,2008,183,9,0,409.8,0.64,220,47.04,287.04,1.726000,33.390000,96890,0.014183
12,OQT,2008-07-02 12:53:00,18.33,75.51,0.00,291.48,8575,2008,183,12,0,369.4,1.08,340,76.38,291.48,1.726000,33.390000,96890,0.016421
13,OQT,2008-07-02 15:53:00,26.11,45.14,0.00,299.26,8590,2008,183,15,0,359.4,0.96,340,51.38,299.26,1.762403,20.682636,96890,0.015762
14,OQT,2008-07-02 18:53:00,29.44,28.74,6.90,302.59,8605,2008,183,18,0,365.5,0.70,320,15.35,302.59,1.464867,11.434903,96890,0.012186
15,OQT,2008-07-02 21:53:00,30.00,30.09,4.60,303.15,8620,2008,183,21,0,432.5,0.32,120,-15.79,303.00,1.479321,12.614586,96890,0.013176
16,OQT,2008-07-03 00:53:00,26.67,42.16,0.00,299.82,8635,2008,184,0,0,488.1,0.48,0,-30.91,299.82,1.768155,18.674803,96890,0.015215
17,OQT,2008-07-03 03:53:00,20.56,65.44,0.00,293.71,8650,2008,184,3,0,519.1,0.35,200,-18.75,293.71,1.726000,33.390000,96890,0.016348
18,OQT,2008-07-03 06:53:00,17.22,80.93,0.00,290.37,8665,2008,184,6,0,540.4,0.21,220,11.16,290.37,1.726000,33.390000,96890,0.016412
19,OQT,2008-07-03 09:53:00,15.56,86.18,0.00,288.71,8680,2008,184,9,0,421.8,0.58,80,46.96,288.71,1.726000,33.390000,96890,0.015723
20,OQT,2008-07-03 12:53:00,20.56,67.59,0.00,293.71,8695,2008,184,12,0,374.0,1.14,220,76.31,293.71,1.726000,33.390000,96890,0.016885
21,OQT,2008-07-03 15:53:00,27.78,40.84,3.45,300.93,8710,2008,184,15,0,363.3,0.91,240,51.37,300.93,1.770703,17.785427,96890,0.015729
22,OQT,2008-07-03 18:53:00,31.11,31.41,9.20,304.26,8725,2008,184,18,0,362.9,0.48,220,15.33,303.00,1.544223,13.070325,96890,0.014655
23,OQT,2008-07-03 21:53:00,31.11,30.39,8.05,304.26,8740,2008,184,21,0,442.4,0.30,100,-15.73,303.00,1.492092,12.745372,96890,0.014179
24,OQT,2008-07-04 00:53:00,28.89,39.83,0.00,302.04,8755,2008,185,0,0,505.0,0.47,80,-30.99,302.04,1.772652,17.104920,96890,0.016361
25,OQT,2008-07-04 03:53:00,23.89,61.66,0.00,297.04,8770,2008,185,3,0,527.9,0.48,300,-18.89,297.04,1.730517,31.813309,96890,0.018863
26,OQT,2008-07-04 06:53:00,22.22,68.35,0.00,295.37,8785,2008,185,6,0,548.3,0.33,260,11.09,295.37,1.726000,33.390000,96890,0.018902
27,OQT,2008-07-04 09:53:00,21.67,75.57,0.00,294.82,8800,2008,185,9,0,413.9,0.60,340,46.88,294.82,1.726000,33.390000,96890,0.020209
28,OQT,2008-07-04 12:53:00,24.44,62.17,3.45,297.59,8815,2008,185,12,0,368.0,1.76,240,76.23,297.59,1.729532,32.156931,96890,0.019657
29,OQT,2008-07-04 15:53:00,28.33,52.93,8.05,301.48,8830,2008,185,15,0,362.8,2.02,220,51.34,301.48,1.747367,25.931301,96890,0.021048
30,OQT,2008-07-04 18:53:00,31.11,39.17,6.90,304.26,8845,2008,185,18,0,364.3,0.63,220,15.32,303.00,1.773926,16.660232,96890,0.018275
31,OQT,2008-07-04 21:53:00,31.67,36.42,4.60,304.82,8860,2008,185,21,0,451.8,0.26,220,-15.81,303.00,1.779234,14.807366,96890,0.017541
32,OQT,2008-07-05 00:53:00,21.67,78.49,3.45,294.82,8875,2008,186,0,0,501.0,0.25,140,-31.08,294.82,1.726000,33.390000,96890,0.020990
33,OQT,2008-07-05 03:53:00,21.11,87.26,0.00,294.26,8890,2008,186,3,0,540.3,0.16,220,-18.99,294.26,1.726000,33.390000,96890,0.022549
34,OQT,2008-07-05 06:53:00,20.56,89.98,0.00,293.71,8905,2008,186,6,0,580.2,0.35,140,11.00,293.71,1.726000,33.390000,96890,0.022478
35,OQT,2008-07-05 09:46:00,21.00,88.34,0.00,294.15,8920,2008,186,9,0,407.1,1.90,240,46.79,294.15,1.726000,33.390000,96890,0.022674
36,OQT,2008-07-05 12:07:00,21.00,88.34,0.00,294.15,8935,2008,186,12,0,367.0,2.29,260,76.13,294.15,1.726000,33.390000,96890,0.022674
37,OQT,2008-07-05 15:02:00,22.00,88.43,8.05,295.15,8950,2008,186,15,0,362.5,2.07,240,51.35,295.15,1.726000,33.390000,96890,0.024129
38,OQT,2008-07-05 18:53:00,28.33,54.63,4.60,301.48,8965,2008,186,18,0,368.9,2.53,240,15.31,301.48,1.744086,27.076709,96890,0.021724
39,OQT,2008-07-05 21:53:00,28.89,49.22,3.45,302.04,8980,2008,186,21,0,404.7,0.39,40,-15.85,302.04,1.754528,23.431616,96890,0.020218
40,OQT,2008-07-06 00:53:00,23.89,73.59,0.00,297.04,8995,2008,187,0,0,465.3,0.23,0,-31.17,297.04,1.726000,33.390000,96890,0.022513
41,OQT,2008-07-06 03:53:00,21.11,90.02,0.00,294.26,9010,2008,187,3,0,530.9,0.32,280,-19.08,294.26,1.726000,33.390000,96890,0.023262
42,OQT,2008-07-06 06:53:00,21.11,87.26,0.00,294.26,9025,2008,187,6,0,552.0,0.60,120,10.91,294.26,1.726000,33.390000,96890,0.022549
43,OQT,2008-07-06 09:53:00,20.56,86.66,0.00,293.71,9040,2008,187,9,0,445.6,1.41,220,46.72,293.71,1.726000,33.390000,96890,0.021649
44,OQT,2008-07-06 12:21:00,21.00,88.34,0.00,294.15,9055,2008,187,12,0,381.4,0.92,200,76.03,294.15,1.726000,33.390000,96890,0.022674
45,OQT,2008-07-06 15:53:00,26.11,64.54,6.90,299.26,9070,2008,187,15,0,368.2,1.47,260,51.30,299.26,1.726000,33.390000,96890,0.022536
46,OQT,2008-07-06 18:53:00,30.56,47.83,6.90,303.71,9085,2008,187,18,0,374.0,0.39,220,15.29,303.00,1.757211,22.495076,96890,0.021627
47,OQT,2008-07-06 21:53:00,31.11,40.44,4.60,304.26,9100,2008,187,21,0,471.2,0.50,60,-15.90,303.00,1.771475,17.515919,96890,0.018868
48,OQT,2008-07-07 00:53:00,29.44,44.59,0.00,302.59,9115,2008,188,0,0,512.2,0.34,340,-31.27,302.59,1.763465,20.312063,96890,0.018907
49,OQT,2008-07-07 03:53:00,23.33,68.57,0.00,296.48,9130,2008,188,3,0,568.6,0.61,60,-19.19,296.48,1.726000,33.390000,96890,0.020282
50,OQT,2008-07-07 06:53:00,20.56,80.86,0.00,293.71,9145,2008,188,6,0,605.2,0.38,100,10.82,293.71,1.726000,33.390000,96890,0.020200
51,OQT,2008-07-07 09:53:00,18.89,83.79,0.00,292.04,9160,2008,188,9,0,411.6,1.53,260,46.53,292.04,1.726000,33.390000,96890,0.018872
52,OQT,2008-07-07 12:53:00,23.33,73.49,5.75,296.48,9175,2008,188,12,0,377.1,1.29,260,75.93,296.48,1.726000,33.390000,96890,0.021737
53,OQT,2008-07-07 15:53:00,29.44,54.90,4.60,302.59,9190,2008,188,15,0,371.8,1.81,260,51.20,302.59,1.743565,27.258626,96890,0.023279
54,OQT,2008-07-07 18:53:00,31.11,42.02,6.90,304.26,9205,2008,188,18,0,376.1,0.79,240,15.37,303.00,1.768425,18.580475,96890,0.019605
55,OQT,2008-07-07 21:53:00,29.44,53.21,0.00,302.59,9220,2008,188,21,0,488.8,0.33,120,-15.96,302.59,1.746827,26.119956,96890,0.022562

In [9]:
from PyDDSBB import DDSBB, DDSBBModel

In [10]:
t_opt = np.zeros([July.shape[0], 3])

for i in np.arange(20):
    sample = July.iloc[i]

    # A much faster way to run gPROMS
    def write_txt(cycle_time, No_Cycle, Ads0_time, input_file = 'inputs.txt'):
        # x are the independent input, K_sb is the adjustable
        parameter_sens = [sample['kf1, bar-1 s-1 (mol/kg)-1']*1e-5, sample['kf2, bar2 s-1']*1e-10]
        geo_inputs = [sample['H2O_vol'], sample['CO2']*1e-6, sample['tmpK'], sample['pressure'], sample['h2o_temperature']]
        f = open(input_file, "w+")
        f.write("Ads0_time"+"\n")
        f.write(str(np.round(Ads0_time))+"\n"+"\n")     

        f.write("Ads_time"+"\n")
        f.write(str(np.round(cycle_time[0]))+"\n"+"\n")

        f.write("Des_time"+"\n")
        f.write(str(np.round(cycle_time[1]))+"\n"+"\n")

        f.write("No_Cycle"+"\n")
        f.write(str(No_Cycle)+"\n"+"\n")

        f.write("kf_1"+"\n")
        f.write(str(parameter_sens[0])+"\n"+"\n")

        f.write("kf_2"+"\n")
        f.write(str(parameter_sens[1])+"\n"+"\n")

        f.write("y_H2O_0"+"\n")
        f.write(str(geo_inputs[0])+"\n"+"\n")

        f.write("y_CO2_0"+"\n")
        f.write(str(geo_inputs[1])+"\n"+"\n")

        f.write("T_feed"+"\n")
        f.write(str(geo_inputs[2])+"\n"+"\n")

        f.write("P_atm"+"\n")
        f.write(str(geo_inputs[3])+"\n"+"\n")

        f.write("T_h2o"+"\n")
        f.write(str(geo_inputs[4])+"\n"+"\n")

        #print(cycle_time)
        f.close()

    Dict = {}

    def sim_output(cycle_time):

        ads = np.round(cycle_time[0])
        Ads0 = ads*2
        vac1 = 5
        vac2 = 200
        vac3 = 100
        des = np.round(cycle_time[1])
        press1 = 20
        press2 = 200
        press3 = 5

        cycle = np.ceil(10000/(cycle_time[0]+cycle_time[1]))

        print(cycle_time, cycle)
        write_txt(cycle_time, No_Cycle = cycle, Ads0_time = Ads0, input_file = 'inputs.txt')

        gORUN_path = 'C:/Program Files/PSE/gPROMS-core_2021.2.0.55235/bin/goRUN.bat'
        gENCRYPT_name = 'H2O_export'
        activity = 'sim'
        process = 'H2O_export'
        password = 'H2O_export'

        call_gORUN(gORUN_path, gENCRYPT_name, activity, process, password, working_dir='./', time_out=24*3600,
                    verbose=True)

        filename = 'C:/Users/xcai65/OneDrive - Georgia Institute of Technology/study/research/NETL/script/Shubham/optimize_prod/output/H2O_export.gPLOT'
        output_results = gPLOT2df(filename)

        report_Des = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1
        report_Ads = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)
        report_Vac3 = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1-des-vac3

        try:
            #output_results['Time'] = np.round(output_results['Time'].values)
            prod_mass = output_results['Channel.PROD_MASS'][output_results['Time'] == report_Des].iloc[0] #mol/kg fiber/hr

            Out_CO2_des = output_results['Channel.OUT_CO2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
            Out_N2_des = output_results['Channel.OUT_N2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
            Out_H2O_des = output_results['Channel.OUT_H2O_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
            In_CO2_ads = output_results['Channel.IN_CO2_ads'][output_results['Time'] == report_Ads].iloc[0] #mol/channel

            Recovery = Out_CO2_des/In_CO2_ads
            Purity_CO2 = Out_CO2_des/(Out_CO2_des+Out_N2_des)

            E_blower = output_results['Channel.E_blower_ash'][output_results['Time'] == report_Ads].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
            E_vac = output_results['Channel.E_vac'][output_results['Time'] == report_Des].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
            Q_sens_ads = -(output_results['Channel.H_ads_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_ads_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
            Q_sens_CO2 = (output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
            Q_sens_H2O = (output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2    
            Q_ads_H2O = 50700*Out_H2O_des*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
            Q_ads_CO2 = (output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Vac3].iloc[0]-\
                        output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2  
            
            E_blower = E_blower*27.78
            E_vac = E_vac*(Out_CO2_des+Out_N2_des)/(Out_CO2_des+Out_N2_des+Out_H2O_des)

        except:
            prod_mass = 0
            Recovery = 0
            Out_CO2_des = 0
            Out_N2_des = 0
            Out_H2O_des = 0
            #Purity_H2O = 0
            E_blower = 0
            E_vac = 0
            Q_sens_ads = 0
            Q_sens_CO2 = 0
            Q_sens_H2O = 0
            Q_ads_H2O = 0
            Q_ads_CO2 = 0
        
        total_cost = (E_blower+E_vac)*0.05+(Q_sens_ads+Q_sens_CO2+Q_ads_CO2+Q_sens_H2O+Q_ads_H2O)*0.015


        if Recovery >= 0.2 and total_cost<=150:
             Dict[tuple(cycle_time)] = 1.
        else:
             Dict[tuple(cycle_time)] = 0.

        print(prod_mass, Recovery, total_cost)


        return prod_mass

    def simulator_cons(cycle_time):

         return Dict[tuple(cycle_time)]

    model = DDSBBModel.Problem()
    model.add_objective(sim_output, sense = 'maximize')

    model.add_variable(100., 2000.)
    model.add_variable(100., 2000.)
    model.add_unknown_constraint(simulator_cons)

    model_solver = DDSBB(20, split_method = 'equal_bisection', \
                            variable_selection = 'longest_side', multifidelity = 'nn', \
                            stop_option = {'absolute_tolerance': 0.05, 'relative_tolerance': 0.05, \
                                            'minimum_bound': 0.05, 'sampling_limit': 300, 'time_limit': 10000})


    model_solver.optimize(model)
    t_opt[i, 0] = model_solver.get_optimum()
    t_opt[i, 1:3] = model_solver.get_optimizer()

    print('Optimized cycle time for Month {} is {}'.format(i, t_opt[i, :]))

[100. 100.] 50.0
gPROMS executed
0 0 0.0
[2000. 2000.] 3.0
gPROMS executed
0.5125078319489333 0.3683956987567587 92.26358343919077
[ 106.43637606 1766.03850845] 6.0
gPROMS executed
0.1689008700139629 1.1938487896673593 212.99938913387666
[1653.96603406  182.86515047] 6.0
gPROMS executed
0.5949364543823007 0.23562150952140906 123.12693298010481
[1006.37999218 1012.94292708] 5.0
gPROMS executed
0.8505552597793449 0.6240942954604173 83.13842567387492
[ 997.90175227 1963.6439366 ] 4.0
gPROMS executed
0.5773006386948971 0.6268328537404784 83.28495262386933
[833.12092829 108.81592387] 11.0
gPROMS executed

KeyboardInterrupt:

In [11]:
print(t_opt)

[[1.31687370e+00 1.78872604e+02 1.08792585e+02]
 [1.13502501e+00 4.23546492e+02 3.67802958e+02]
 [1.10046559e+00 6.37218284e+02 5.34790754e+02]
 [8.87999159e-01 1.08590883e+03 7.75780581e+02]
 [9.33051237e-01 7.46653290e+02 5.08263453e+02]
 [1.01056709e+00 3.00017968e+02 1.71904048e+02]
 [9.84733509e-01 2.51546017e+02 1.56184249e+02]
 [1.16768843e+00 1.66867914e+02 1.07072864e+02]
 [1.27939949e+00 1.60998259e+02 1.21254789e+02]
 [1.19082350e+00 5.12543378e+02 4.40965221e+02]
 [1.16885572e+00 5.25090643e+02 4.94549678e+02]
 [9.58353859e-01 8.28584471e+02 6.07691977e+02]
 [9.15669339e-01 7.80240397e+02 5.60323030e+02]
 [9.24407612e-01 4.58444860e+02 2.82730233e+02]
 [9.35658846e-01 2.94023740e+02 1.86385606e+02]
 [1.08573991e+00 1.96267518e+02 1.23910340e+02]
 [1.15964978e+00 3.68682237e+02 2.01206133e+02]
 [1.18709619e+00 5.80302359e+02 4.57631060e+02]
 [1.15886480e+00 4.90337506e+02 4.68815826e+02]
 [9.63926972e-01 7.28838500e+02 7.01997065e+02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]

In [12]:
df_out = pd.DataFrame(t_opt, columns=['Optimized Productivity, mol/kg/hr', 'Ads_t, s', 'Des_t, s'])

July = July.reset_index(drop=True)
July = pd.concat([July, df_out], axis = 1)
July

,station,valid,tmpc,relh,sped,tmpK,index,YEAR,DOY,HOUR,...,WIND_DIR,SOLAR_ANG,h2o_temperature,"kf1, bar-1 s-1 (mol/kg)-1","kf2, bar2 s-1",pressure,H2O_vol,"Optimized Productivity, mol/kg/hr","Ads_t, s","Des_t, s"
0,OQT,2008-07-01 00:53:00,22.78,42.48,3.45,295.93,8395,2008,182,0,...,260,-30.77,295.93,1.767537,18.890409,96890,0.012154,1.316874,178.872604,108.792585
1,OQT,2008-07-01 03:53:00,16.67,69.51,0.00,289.82,8410,2008,182,3,...,220,-18.63,289.82,1.726000,33.390000,96890,0.013613,1.135025,423.546492,367.802958
2,OQT,2008-07-01 06:53:00,13.89,83.21,0.00,287.04,8425,2008,182,6,...,260,11.32,287.04,1.726000,33.390000,96890,0.013631,1.100466,637.218284,534.790754
3,OQT,2008-07-01 09:53:00,12.22,89.95,0.00,285.37,8440,2008,182,9,...,240,47.09,285.37,1.726000,33.390000,96890,0.013210,0.887999,1085.908827,775.780581
4,OQT,2008-07-01 12:53:00,17.78,72.53,0.00,290.93,8455,2008,182,12,...,220,76.47,290.93,1.726000,33.390000,96890,0.015237,0.933051,746.653290,508.263453
5,OQT,2008-07-01 15:53:00,25.56,37.38,5.75,298.71,8470,2008,182,15,...,260,51.45,298.71,1.777381,15.454184,96890,0.012634,1.010567,300.017968,171.904048
6,OQT,2008-07-01 18:53:00,27.78,32.84,0.00,300.93,8485,2008,182,18,...,320,15.35,300.93,1.617310,13.525897,96890,0.012648,0.984734,251.546017,156.184249
7,OQT,2008-07-01 21:53:00,28.89,26.55,5.75,302.04,8500,2008,182,21,...,240,-15.69,302.04,1.441419,9.521196,96890,0.010906,1.167688,166.867914,107.072864
8,OQT,2008-07-02 00:53:00,25.00,38.74,0.00,298.15,8515,2008,183,0,...,0,-30.83,298.15,1.774756,16.370511,96890,0.012665,1.279399,160.998259,121.254789
9,OQT,2008-07-02 03:53:00,18.33,70.28,0.00,291.48,8530,2008,183,3,...,260,-18.71,291.48,1.726000,33.390000,96890,0.015284,1.190823,512.543378,440.965221
10,OQT,2008-07-02 06:53:00,15.56,80.19,0.00,288.71,8545,2008,183,6,...,260,11.24,288.71,1.726000,33.390000,96890,0.014630,1.168856,525.090643,494.549678
11,OQT,2008-07-02 09:53:00,13.89,86.58,0.00,287.04,8560,2008,183,9,...,220,47.04,287.04,1.726000,33.390000,96890,0.014183,0.958354,828.584471,607.691977
12,OQT,2008-07-02 12:53:00,18.33,75.51,0.00,291.48,8575,2008,183,12,...,340,76.38,291.48,1.726000,33.390000,96890,0.016421,0.915669,780.240397,560.323030
13,OQT,2008-07-02 15:53:00,26.11,45.14,0.00,299.26,8590,2008,183,15,...,340,51.38,299.26,1.762403,20.682636,96890,0.015762,0.924408,458.444860,282.730233
14,OQT,2008-07-02 18:53:00,29.44,28.74,6.90,302.59,8605,2008,183,18,...,320,15.35,302.59,1.464867,11.434903,96890,0.012186,0.935659,294.023740,186.385606
15,OQT,2008-07-02 21:53:00,30.00,30.09,4.60,303.15,8620,2008,183,21,...,120,-15.79,303.00,1.479321,12.614586,96890,0.013176,1.085740,196.267518,123.910340
16,OQT,2008-07-03 00:53:00,26.67,42.16,0.00,299.82,8635,2008,184,0,...,0,-30.91,299.82,1.768155,18.674803,96890,0.015215,1.159650,368.682237,201.206133
17,OQT,2008-07-03 03:53:00,20.56,65.44,0.00,293.71,8650,2008,184,3,...,200,-18.75,293.71,1.726000,33.390000,96890,0.016348,1.187096,580.302359,457.631060
18,OQT,2008-07-03 06:53:00,17.22,80.93,0.00,290.37,8665,2008,184,6,...,220,11.16,290.37,1.726000,33.390000,96890,0.016412,1.158865,490.337506,468.815826
19,OQT,2008-07-03 09:53:00,15.56,86.18,0.00,288.71,8680,2008,184,9,...,80,46.96,288.71,1.726000,33.390000,96890,0.015723,0.963927,728.838500,701.997065
20,OQT,2008-07-03 12:53:00,20.56,67.59,0.00,293.71,8695,2008,184,12,...,220,76.31,293.71,1.726000,33.390000,96890,0.016885,0.000000,0.000000,0.000000
21,OQT,2008-07-03 15:53:00,27.78,40.84,3.45,300.93,8710,2008,184,15,...,240,51.37,300.93,1.770703,17.785427,96890,0.015729,0.000000,0.000000,0.000000
22,OQT,2008-07-03 18:53:00,31.11,31.41,9.20,304.26,8725,2008,184,18,...,220,15.33,303.00,1.544223,13.070325,96890,0.014655,0.000000,0.000000,0.000000
23,OQT,2008-07-03 21:53:00,31.11,30.39,8.05,304.26,8740,2008,184,21,...,100,-15.73,303.00,1.492092,12.745372,96890,0.014179,0.000000,0.000000,0.000000
24,OQT,2008-07-04 00:53:00,28.89,39.83,0.00,302.04,8755,2008,185,0,...,80,-30.99,302.04,1.772652,17.104920,96890,0.016361,0.000000,0.000000,0.000000
25,OQT,2008-07-04 03:53:00,23.89,61.66,0.00,297.04,8770,2008,185,3,...,300,-18.89,297.04,1.730517,31.813309,96890,0.018863,0.000000,0.000000,0.000000
26,OQT,2008-07-04 06:53:00,22.22,68.35,0.00,295.37,8785,2008,185,6,...,260,11.09,295.37,1.726000,33.390000,96890,0.018902,0.000000,0.000000,0.000000
27,OQT,2008-07-04 09:53:00,21.67,75.57,0.00,294.82,8800,2008,185,9,...,340,46.88,294.82,1.726000,33.390000,96890,0.020209,0.000000,0.000000,0.000000
28,OQT,2008-07-04 12:53:00,24.44,62.17,3.45,297.59,8815,2008,185,12,...,240,76.23,297.59,1.729532,32.156931,96890,0.019657,0.000000,0.000000,0.000000
29,OQT,2008-07-04 15:53:00,28.33,52.93,8.05,301.48,8830,2008,185,15,...,220,51.34,301.48,1.747367,25.931301,96890,0.021048,0.000000,0.000000,0.000000
30,OQT,2008-07-04 18:53:00,31.11,39.17,6.90,304.26,8845,2008,185,18,...,220,15.32,303.00,1.773926,16.660232,96890,0.018275,0.000000,0.000000,0.000000
31,OQT,2008-07-04 21:53:00,31.67,36.42,4.60,304.82,8860,2008,185,21,...,220,-15.81,303.00,1.779234,14.807366,96890,0.017541,0.000000,0.000000,0.000000
32,OQT,2008-07-05 00:53:00,21.67,78.49,3.45,294.82,8875,2008,186,0,...,140,-31.08,294.82,1.726000,33.390000,96890,0.020990,0.000000,0.000000,0.000000
33,OQT,2008-07-05 03:53:00,21.11,87.26,0.00,294.26,8890,2008,186,3,...,220,-18.99,294.26,1.726000,33.390000,96890,0.022549,0.000000,0.000000,0.000000
34,OQT,2008-07-05 06:53:00,20.56,89.98,0.00,293.71,8905,2008,186,6,...,140,11.00,293.71,1.726000,33.390000,96890,0.022478,0.000000,0.000000,0.000000
35,OQT,2008-07-05 09:46:00,21.00,88.34,0.00,294.15,8920,2008,186,9,...,240,46.79,294.15,1.726000,33.390000,96890,0.022674,0.000000,0.000000,0.000000
36,OQT,2008-07-05 12:07:00,21.00,88.34,0.00,294.15,8935,2008,186,12,...,260,76.13,294.15,1.726000,33.390000,96890,0.022674,0.000000,0.000000,0.000000
37,OQT,2008-07-05 15:02:00,22.00,88.43,8.05,295.15,8950,2008,186,15,...,240,51.35,295.15,1.726000,33.390000,96890,0.024129,0.000000,0.000000,0.000000
38,OQT,2008-07-05 18:53:00,28.33,54.63,4.60,301.48,8965,2008,186,18,...,240,15.31,301.48,1.744086,27.076709,96890,0.021724,0.000000,0.000000,0.000000
39,OQT,2008-07-05 21:53:00,28.89,49.22,3.45,302.04,8980,2008,186,21,...,40,-15.85,302.04,1.754528,23.431616,96890,0.020218,0.000000,0.000000,0.000000
40,OQT,2008-07-06 00:53:00,23.89,73.59,0.00,297.04,8995,2008,187,0,...,0,-31.17,297.04,1.726000,33.390000,96890,0.022513,0.000000,0.000000,0.000000
41,OQT,2008-07-06 03:53:00,21.11,90.02,0.00,294.26,9010,2008,187,3,...,280,-19.08,294.26,1.726000,33.390000,96890,0.023262,0.000000,0.000000,0.000000
42,OQT,2008-07-06 06:53:00,21.11,87.26,0.00,294.26,9025,2008,187,6,...,120,10.91,294.26,1.726000,33.390000,96890,0.022549,0.000000,0.000000,0.000000
43,OQT,2008-07-06 09:53:00,20.56,86.66,0.00,293.71,9040,2008,187,9,...,220,46.72,293.71,1.726000,33.390000,96890,0.021649,0.000000,0.000000,0.000000
44,OQT,2008-07-06 12:21:00,21.00,88.34,0.00,294.15,9055,2008,187,12,...,200,76.03,294.15,1.726000,33.390000,96890,0.022674,0.000000,0.000000,0.000000
45,OQT,2008-07-06 15:53:00,26.11,64.54,6.90,299.26,9070,2008,187,15,...,260,51.30,299.26,1.726000,33.390000,96890,0.022536,0.000000,0.000000,0.000000
46,OQT,2008-07-06 18:53:00,30.56,47.83,6.90,303.71,9085,2008,187,18,...,220,15.29,303.00,1.757211,22.495076,96890,0.021627,0.000000,0.000000,0.000000
47,OQT,2008-07-06 21:53:00,31.11,40.44,4.60,304.26,9100,2008,187,21,...,60,-15.90,303.00,1.771475,17.515919,96890,0.018868,0.000000,0.000000,0.000000
48,OQT,2008-07-07 00:53:00,29.44,44.59,0.00,302.59,9115,2008,188,0,...,340,-31.27,302.59,1.763465,20.312063,96890,0.018907,0.000000,0.000000,0.000000
49,OQT,2008-07-07 03:53:00,23.33,68.57,0.00,296.48,9130,2008,188,3,...,60,-19.19,296.48,1.726000,33.390000,96890,0.020282,0.000000,0.000000,0.000000
50,OQT,2008-07-07 06:53:00,20.56,80.86,0.00,293.71,9145,2008,188,6,...,100,10.82,293.71,1.726000,33.390000,96890,0.020200,0.000000,0.000000,0.000000
51,OQT,2008-07-07 09:53:00,18.89,83.79,0.00,292.04,9160,2008,188,9,...,260,46.53,292.04,1.726000,33.390000,96890,0.018872,0.000000,0.000000,0.000000
52,OQT,2008-07-07 12:53:00,23.33,73.49,5.75,296.48,9175,2008,188,12,...,260,75.93,296.48,1.726000,33.390000,96890,0.021737,0.000000,0.000000,0.000000
53,OQT,2008-07-07 15:53:00,29.44,54.90,4.60,302.59,9190,2008,188,15,...,260,51.20,302.59,1.743565,27.258626,96890,0.023279,0.000000,0.000000,0.000000
54,OQT,2008-07-07 18:53:00,31.11,42.02,6.90,304.26,9205,2008,188,18,...,240,15.37,303.00,1.768425,18.580475,96890,0.019605,0.000000,0.000000,0.000000
55,OQT,2008-07-07 21:53:00,29.44,53.21,0.00,302.59,9220,2008,188,21,...,120,-15.96,302.59,1.746827,26.119956,96890,0.022562,0.000000,0.000000,0.000000

In [13]:
July.to_csv('July_prod_20.csv')

In [17]:
def write_txt(parameter_sens, geo_inputs, cycle_time, No_Cycle, Ads0_time, input_file = 'inputs.txt'):
    # x are the independent input, K_sb is the adjustable
    f = open(input_file, "w+")
    f.write("Ads0_time"+"\n")
    f.write(str(np.round(Ads0_time))+"\n"+"\n")     

    f.write("Ads_time"+"\n")
    f.write(str(np.round(cycle_time[0]))+"\n"+"\n")

    f.write("Des_time"+"\n")
    f.write(str(np.round(cycle_time[1]))+"\n"+"\n")

    f.write("No_Cycle"+"\n")
    f.write(str(No_Cycle)+"\n"+"\n")

    f.write("kf_1"+"\n")
    f.write(str(parameter_sens[0])+"\n"+"\n")

    f.write("kf_2"+"\n")
    f.write(str(parameter_sens[1])+"\n"+"\n")

    f.write("y_H2O_0"+"\n")
    f.write(str(geo_inputs[0])+"\n"+"\n")

    f.write("y_CO2_0"+"\n")
    f.write(str(geo_inputs[1])+"\n"+"\n")

    f.write("T_feed"+"\n")
    f.write(str(geo_inputs[2])+"\n"+"\n")

    f.write("P_atm"+"\n")
    f.write(str(geo_inputs[3])+"\n"+"\n")

    f.write("T_h2o"+"\n")
    f.write(str(geo_inputs[4])+"\n"+"\n")

    #print(cycle_time)
    f.close()
    
def sim_output(parameter_sens, geo_inputs, cycle_time):

    ads = np.round(cycle_time[0])
    Ads0 = ads*2
    vac1 = 5
    vac2 = 200
    vac3 = 100
    des = np.round(cycle_time[1])
    press1 = 20
    press2 = 200
    press3 = 5

    cycle = np.ceil(10000/(cycle_time[0]+cycle_time[1]))

    print(cycle_time, cycle)
    write_txt(parameter_sens, geo_inputs, cycle_time, No_Cycle = cycle, Ads0_time = Ads0, input_file = 'inputs.txt')


    gORUN_path = 'C:/Program Files/PSE/gPROMS-core_2021.2.0.55235/bin/goRUN.bat'
    gENCRYPT_name = 'H2O_export'
    activity = 'sim'
    process = 'H2O_export'
    password = 'H2O_export'

    call_gORUN(gORUN_path, gENCRYPT_name, activity, process, password, working_dir='./', time_out=24*3600,
                verbose=True)

    filename = 'C:/Users/xcai65/OneDrive - Georgia Institute of Technology/study/research/NETL/script/FACE/prod/output/H2O_export.gPLOT'
    output_results = gPLOT2df(filename)

    report_Des = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1
    report_Ads = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)
    report_Vac3 = Ads0+vac1+vac2+vac3+des+press1+press2+press3+ads+(vac1+vac2+vac3+des+press1+press2+press3+ads)*(cycle-1)-ads-press3-press2-press1-des-vac3

    try:
        #output_results['Time'] = np.round(output_results['Time'].values)
        prod_mass = output_results['Channel.PROD_MASS'][output_results['Time'] == report_Des].iloc[0] #mol/kg fiber/hr

        Out_CO2_des = output_results['Channel.OUT_CO2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
        Out_N2_des = output_results['Channel.OUT_N2_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
        Out_H2O_des = output_results['Channel.OUT_H2O_des'][output_results['Time'] == report_Des].iloc[0] #mol/channel
        In_CO2_ads = output_results['Channel.IN_CO2_ads'][output_results['Time'] == report_Ads].iloc[0] #mol/channel

        Recovery = Out_CO2_des/In_CO2_ads
        Purity_CO2 = Out_CO2_des/(Out_CO2_des+Out_N2_des)
        #Purity_H2O = Out_H2O_des/(Out_CO2_des+Out_N2_des+Out_H2O_des)

        E_blower = output_results['Channel.E_blower_ash'][output_results['Time'] == report_Ads].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
        E_vac = output_results['Channel.E_vac'][output_results['Time'] == report_Des].iloc[0]/(Out_CO2_des*44.02*1e-6) # kWh/tCO2
        Q_sens_ads = -(output_results['Channel.H_ads_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_ads_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
        Q_sens_CO2 = (output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_CO2_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
        Q_sens_H2O = (output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_H2O_sens'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2    
        Q_ads_H2O = 50700*Out_H2O_des*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2
        Q_ads_CO2 = (output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Vac3].iloc[0]-\
                    output_results['Channel.H_ads_CO2'][output_results['Time'] == report_Des].iloc[0])*1e-3/(Out_CO2_des*44.02*1e-6)/3600 # kWh/tCO2  

        E_blower = E_blower*27.78
        E_vac = E_vac*(Out_CO2_des+Out_N2_des)/(Out_CO2_des+Out_N2_des+Out_H2O_des)

    except:
        prod_mass = 0
        Recovery = 0
        Out_CO2_des = 0
        Out_N2_des = 0
        Out_H2O_des = 0
        #Purity_H2O = 0
        E_blower = 0
        E_vac = 0
        Q_sens_ads = 0
        Q_sens_CO2 = 0
        Q_sens_H2O = 0
        Q_ads_H2O = 0
        Q_ads_CO2 = 0



    return ([E_blower, E_vac, Q_sens_ads, Q_sens_CO2, Q_sens_H2O, Q_ads_CO2, Q_ads_H2O])

In [18]:
output_E = np.zeros([20, 7])

for i in range(July.shape[0]):
    sample = July.iloc[i, :]
    parameter_sens = [sample['kf1, bar-1 s-1 (mol/kg)-1']*1e-5, sample['kf2, bar2 s-1']*1e-10]
    geoinputs = [sample['H2O_vol'], sample['CO2']*1e-6, sample['tmpK'], sample['pressure'], sample['h2o_temperature']]
    cycle_time = [sample['Ads_t, s'], sample['Des_t, s']]

    output_E[i, :]= sim_output(parameter_sens, geoinputs, cycle_time)
    print(output_E[i, :],  i)

[178.87260424358078, 108.7925848980773] 35.0
gPROMS executed
[ 376.32745163  125.16243707 5314.06966308   20.49569787  392.52786127
  623.06754253 1599.41784033] 0
[423.54649204165634, 367.8029584101103] 13.0
gPROMS executed
[ 376.22252436  118.72075799 2708.70209625   50.31317528 1155.17450474
  635.45933531 2979.61726278] 1
[637.2182839647917, 534.7907536338267] 9.0
gPROMS executed
[ 393.95281861  116.60952327 2042.91749228   55.60178698 1336.66560214
  638.03111579 3329.28525458] 2
[1085.9088269268912, 775.7805812848616] 6.0
gPROMS executed
[ 523.71974522  115.30889255 1753.59900866   59.85535138 1532.02307405
  639.38748709 3745.64384446] 3
[746.6532901127848, 508.2634531750218] 8.0
gPROMS executed
[ 508.54545695  117.15534764 2169.70092275   56.85064944 1293.44591686
  639.76533917 3189.09977657] 4
[300.01796753305143, 171.9040483605013] 22.0
gPROMS executed
[ 501.20270795  124.72491889 4495.77362357   40.91982069  466.7874555
  627.97569623 1527.32016495] 5
[251.5460165067123, 156.1842485383152] 25.0
gPROMS executed
[ 499.81157622  126.74778312 5275.77308368   38.93066764  368.44580116
  628.38436047 1351.973714  ] 6
[166.86791400967067, 107.07286363937195] 37.0
gPROMS executed
[ 415.94539637  129.4732387  6489.28504784   26.35672291  119.14452301
  632.32877444  866.52273426] 7
[160.99825939225002, 121.25478877520482] 36.0
gPROMS executed
[ 355.80141127  126.5048625  5688.55883059   26.37963248  389.51507291
  624.53488558 1555.95605321] 8
[512.5433778676352, 440.96522099435197] 11.0
gPROMS executed
[ 360.12155087  117.70337919 2170.43559448   55.72362922 1100.6881721
  639.1726059  2749.88638913] 9
[525.0906429354361, 494.5496780347895] 10.0
gPROMS executed
[ 351.29231294  117.14773794 2154.22917847   55.29995411 1281.99766791
  638.33492392 3196.95076557] 10
[828.5844709076684, 607.691976799238] 7.0
gPROMS executed
[ 480.05827727  115.85147449 1933.1791937    56.79206873 1531.64648324
  639.1798407  3768.15940026] 11
[780.240396875279, 560.3230296607817] 8.0
gPROMS executed
[ 506.79672941  116.76541389 2089.9463302    58.22599518 1396.95225705
  641.19280686 3405.55562434] 12
[458.4448599874273, 282.73023276921026] 14.0
gPROMS executed
[ 532.80232929  121.88051607 3245.02509951   52.95013985  745.5498777
  633.07343821 1989.18735927] 13
[294.023739990932, 186.3856061565342] 21.0
gPROMS executed
[ 521.59267795  126.95797041 4855.2203952    45.8617904   290.64875155
  631.42560236 1067.90050377] 14
[196.26751815527768, 123.91034030972898] 32.0
gPROMS executed
[ 449.52222965  127.96437061 5804.81530585   33.12081993  263.74714179
  627.64359748 1165.60332204] 15
[368.68223707475926, 201.20613343935224] 18.0
gPROMS executed
[ 444.8767395   121.6879133  3098.7551866    47.90215042  546.03916806
  630.62502279 1558.48570665] 16
[580.3023593132837, 457.6310597510365] 10.0
gPROMS executed
[ 375.25780182  117.74220663 1988.04921528   58.35049456  975.22608721
  641.46130492 2409.82614232] 17
[490.33750602640544, 468.81582617096774] 11.0
gPROMS executed
[ 351.76187205  117.06500212 2201.77238703   54.34504289 1384.91363269
  639.22637304 3436.68134578] 18
[728.8384997199074, 701.997064760078] 7.0
gPROMS executed
[ 421.52851925  116.32980164 2019.24213187   59.78725196 1536.59900433
  640.41507163 3738.04256934] 19
[0.0, 0.0] inf
gPROMS executed

C:\Users\xcai65\AppData\Local\Temp\ipykernel_4520\2180048781.py:52: RuntimeWarning: divide by zero encountered in double_scalars
  cycle = np.ceil(10000/(cycle_time[0]+cycle_time[1]))

IndexError: index 20 is out of bounds for axis 0 with size 20

In [ ]:
df_output_E = pd.DataFrame(output_E, columns = ['E_blower', 'E_vac', 'Q_sens_ads', 'Q_sens_CO2', 'Q_sens_H2O', 'Q_ads_CO2', 'Q_ads_H2O'])
df_output_E['Cost_E, $/tCO2'] = df_output_E.iloc[:, :2].sum(axis = 1)*0.05
df_output_E['Cost_H, $/tCO2'] = df_output_E.iloc[:, 2:7].sum(axis = 1)*0.015

df_final = pd.concat([July, df_output_E], axis = 1)
df_final.to_csv('July_prod_20.csv')